#! /bin/bash
hostnames=(ec2-54-85-32-37.compute-1.amazonaws.com
    ec2-54-193-70-31.us-west-1.compute.amazonaws.com
    ec2-52-38-67-246.us-west-2.compute.amazonaws.com
    ec2-52-51-20-200.eu-west-1.compute.amazonaws.com
    ec2-52-29-65-165.eu-central-1.compute.amazonaws.com
    ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com
    ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com
    ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com
    ec2-54-233-185-94.sa-east-1.compute.amazonaws.com)
h1="ec2-54-85-32-37.compute-1.amazonaws.com"
h2="ec2-54-193-70-31.us-west-1.compute.amazonaws.com"
h3="ec2-52-38-67-246.us-west-2.compute.amazonaws.com"
h4="ec2-52-51-20-200.eu-west-1.compute.amazonaws.com"
h5="ec2-52-29-65-165.eu-central-1.compute.amazonaws.com"
h6="ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com"
h7="ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com"
h8= "ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com"
h9="ec2-54-233-185-94.sa-east-1.compute.amazonaws.com"

while getopts "p:o:n:u:i:" options; do
	case $options in
		p) port=$OPTARG
			;;
		o) origin=$OPTARG
			;;
		n) name=$OPTARG
			;;
		u) username=$OPTARG
			;;
		i) keyfile=$OPTARG
			;;
	esac
done


ssh -i $keyfile ${username}@${h1} 'mkdir ~/CDN/'
scp -i $keyfile ping.py ${username}@${h1}:~/CDN/
scp -i $keyfile httpserver ${username}@${h1}:~/CDN/

ssh -i $keyfile ${username}@${h1} 'mkdir ~/CDN/'
scp -i $keyfile ping.py ${username}@${h1}:~/CDN/
scp -i $keyfile httpserver ${username}@${h1}:~/CDN/

ssh -i $keyfile ${username}@${h1} 'mkdir ~/CDN/'
scp -i $keyfile ping.py ${username}@${h1}:~/CDN/
scp -i $keyfile httpserver ${username}@${h1}:~/CDN/

ssh -i $keyfile ${username}@${h1} 'mkdir ~/CDN/'
scp -i $keyfile ping.py ${username}@${h1}:~/CDN/
scp -i $keyfile httpserver ${username}@${h1}:~/CDN/

ssh -i $keyfile ${username}@${h1} 'mkdir ~/CDN/'
scp -i $keyfile ping.py ${username}@${h1}:~/CDN/
scp -i $keyfile httpserver ${username}@${h1}:~/CDN/

ssh -i $keyfile ${username}@${h1} 'mkdir ~/CDN/'
scp -i $keyfile ping.py ${username}@${h1}:~/CDN/
scp -i $keyfile httpserver ${username}@${h1}:~/CDN/

ssh -i $keyfile ${username}@${h1} 'mkdir ~/CDN/'
scp -i $keyfile ping.py ${username}@${h1}:~/CDN/
scp -i $keyfile httpserver ${username}@${h1}:~/CDN/

ssh -i $keyfile ${username}@${h1} 'mkdir ~/CDN/'
scp -i $keyfile ping.py ${username}@${h1}:~/CDN/
scp -i $keyfile httpserver ${username}@${h1}:~/CDN/

ssh -i $keyfile ${username}@${h1} 'mkdir ~/CDN/'
scp -i $keyfile ping.py ${username}@${h1}:~/CDN/
scp -i $keyfile httpserver ${username}@${h1}:~/CDN/
dns_server=cs5700cdnproject.ccs.neu.edu
echo "Deploy " $dns_server
ssh -i $keyfile ${username}@${cs5700cdnproject.ccs.neu.edu} 'mkdir ~/CDN/'
scp -i $keyfile dnsserver ${username}@${cs5700cdnproject.ccs.neu.edu}:~/CDN/
scp -i $keyfile mapper.py ${username}@${cs5700cdnproject.ccs.neu.edu}:~/CDN/

