#!/bin/bash
hostnames=(ec2-54-85-32-37.compute-1.amazonaws.com
ec2-54-193-70-31.us-west-1.compute.amazonaws.com
    ec2-52-38-67-246.us-west-2.compute.amazonaws.com
    ec2-52-51-20-200.eu-west-1.compute.amazonaws.com
    ec2-52-29-65-165.eu-central-1.compute.amazonaws.com
    ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com
    ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com
    ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com
    ec2-54-233-185-94.sa-east-1.compute.amazonaws.com)

while getopts "p:o:n:u:i:" options; do
        case $options in
                p) port=$OPTARG
                        ;;
                o) origin=$OPTARG
                        ;;
                n) name=$OPTARG
                        ;;
                u) username=$OPTARG
                        ;;
                i) keyfile=$OPTARG
                        ;;
        esac
done


dnsserver=cs5700cdnproject.ccs.neu.edu
echo "Run " $dnsserver
ssh -i $keyfile -n -f ${username}@ "sh -c 'cd ~/CDN/; nohup ./dnsserver -p $port -n $name > /dev/null 2>&1 &'"


ssh -i $keyfile -n -f ${username}@ec2-54-85-32-37.compute-1.amazonaws.com "sh -c 'cd ~/CDN/; nohup python ping.py > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-54-85-32-37.compute-1.amazonaws.com "sh -c 'cd ~/CDN/; nohup ./httpserver -p $port -o $origin > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-54-193-70-31.us-west-1.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup python ping.py > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-54-193-70-31.us-west-1.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup ./httpserver -p $port -o $origin > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-52-38-67-246.us-west-2.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup python ping.py > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-52-38-67-246.us-west-2.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup ./httpserver -p $port -o $origin > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-52-51-20-200.eu-west-1.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup python ping.py > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-52-51-20-200.eu-west-1.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup ./httpserver -p $port -o $origin > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-52-29-65-165.eu-central-1.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup python ping.py > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-52-29-65-165.eu-central-1.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup ./httpserver -p $port -o $origin > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup python ping.py > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup ./httpserver -p $port -o $origin > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup python ping.py > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup ./httpserver -p $port -o $origin > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup python ping.py > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-54-233-185-94.sa-east-1.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup ./httpserver -p $port -o $origin > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f ${username}@ec2-54-233-185-94.sa-east-1.compute.amazonaws.com "sh -c 'cd ~/CDN/; nohup python ping.py > /dev/null 2>&1 &'"


