#!/bin/bash
h1="ec2-54-85-32-37.compute-1.amazonaws.com"
h2="ec2-54-193-70-31.us-west-1.compute.amazonaws.com"
h3="ec2-52-38-67-246.us-west-2.compute.amazonaws.com"
h4="ec2-52-51-20-200.eu-west-1.compute.amazonaws.com"
h5="ec2-52-29-65-165.eu-central-1.compute.amazonaws.com"
h6="ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com"
h7="ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com"
h8= "ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com"
h9="ec2-54-233-185-94.sa-east-1.compute.amazonaws.com"

while getopts "p:o:n:u:i:" options; do
        case $options in
                p) port=$OPTARG
                        ;;
                o) origin=$OPTARG
                        ;;
                n) name=$OPTARG
                        ;;
                u) username=$OPTARG                        ;;
                i) keyfile=$OPTARG                        ;;
        esac
done
ssh -t -oStrictHostKeyChecking=no -i $keyfile ${username}@${h1} << ENDSSH &> /dev/null 
pkill -f httpserver &> /dev/null
exit
ENDSSH
ssh -t -oStrictHostKeyChecking=no -i $keyfile ${username}@${h2} << ENDSSH &> /dev/null 
pkill -f httpserver &> /dev/null
exit
ENDSSH
ssh -t -oStrictHostKeyChecking=no -i $keyfile ${username}@${h3} << ENDSSH &> /dev/null 
pkill -f httpserver &> /dev/null
exit
ENDSSH
ssh -t -oStrictHostKeyChecking=no -i $keyfile ${username}@${h4} << ENDSSH &> /dev/null 
pkill -f httpserver &> /dev/null
exit
ENDSSH
ssh -t -oStrictHostKeyChecking=no -i $keyfile ${username}@${h5} << ENDSSH &> /dev/null 
pkill -f httpserver &> /dev/null
exit
ENDSSH
ssh -t -oStrictHostKeyChecking=no -i $keyfile ${username}@${h6} << ENDSSH &> /dev/null 
pkill -f httpserver &> /dev/null
exit
ENDSSH
ssh -t -oStrictHostKeyChecking=no -i $keyfile ${username}@${h7} << ENDSSH &> /dev/null 
pkill -f httpserver &> /dev/null
exit
ENDSSH
ssh -t -oStrictHostKeyChecking=no -i $keyfile ${username}@${h8} << ENDSSH &> /dev/null 
pkill -f httpserver &> /dev/null
exit
ENDSSH
ssh -t -oStrictHostKeyChecking=no -i $keyfile ${username}@${h8} << ENDSSH &> /dev/null 
pkill -f httpserver &> /dev/null
exit
ENDSSH
ssh -t -oStrictHostKeyChecking=no -i $keyfile ${username}@${h9} << ENDSSH &> /dev/null 
pkill -f httpserver &> /dev/null
exit
ENDSSH
ssh -t -oStrictHostKeyChecking=no -i $keyfile $username@cs5700cdnproject.ccs.neu.edu << ENDSSH &> /dev/null	
pkill -f dnsserver &> /dev/null	
exit
ENDSSH



